In [1]:
import numpy as np
import pandas as pd

from scipy.io import arff



In [3]:
data, meta = arff.loadarff("../../data/raw/seismic-bumps.arff")
data = np.array(data.tolist())    # unless its one dim vector with np.void
print(data)
print(meta)

[[b'a' b'a' b'N' ... b'0.0' b'0.0' b'0']
 [b'a' b'a' b'N' ... b'2000.0' b'2000.0' b'0']
 [b'a' b'a' b'N' ... b'0.0' b'0.0' b'0']
 ...
 [b'b' b'a' b'W' ... b'0.0' b'0.0' b'0']
 [b'a' b'a' b'W' ... b'0.0' b'0.0' b'0']
 [b'a' b'a' b'W' ... b'0.0' b'0.0' b'0']]
Dataset: seismic-bumps
	seismic's type is nominal, range is ('a', 'b', 'c', 'd')
	seismoacoustic's type is nominal, range is ('a', 'b', 'c', 'd')
	shift's type is nominal, range is ('W', 'N')
	genergy's type is numeric
	gpuls's type is numeric
	gdenergy's type is numeric
	gdpuls's type is numeric
	ghazard's type is nominal, range is ('a', 'b', 'c', 'd')
	nbumps's type is numeric
	nbumps2's type is numeric
	nbumps3's type is numeric
	nbumps4's type is numeric
	nbumps5's type is numeric
	nbumps6's type is numeric
	nbumps7's type is numeric
	nbumps89's type is numeric
	energy's type is numeric
	maxenergy's type is numeric
	class's type is nominal, range is ('1', '0')



In [4]:
df = pd.DataFrame(data, dtype=str)
print(f"Nans number: {np.sum(df.apply(lambda x: sum(x.isnull()), axis=0))}")

Nans number: 0


In [5]:
names = np.array(meta.names())
types = np.array(meta.types())
print(names)
print(types)


['seismic' 'seismoacoustic' 'shift' 'genergy' 'gpuls' 'gdenergy' 'gdpuls'
 'ghazard' 'nbumps' 'nbumps2' 'nbumps3' 'nbumps4' 'nbumps5' 'nbumps6'
 'nbumps7' 'nbumps89' 'energy' 'maxenergy' 'class']
['nominal' 'nominal' 'nominal' 'numeric' 'numeric' 'numeric' 'numeric'
 'nominal' 'numeric' 'numeric' 'numeric' 'numeric' 'numeric' 'numeric'
 'numeric' 'numeric' 'numeric' 'numeric' 'nominal']


In [6]:
categ_features = (types == 'nominal') & (names != 'class')
cont_features = (types == 'numeric')
x_categ = data[:, categ_features].astype('<U14')
x_cont = data[:, cont_features].astype(np.float64)

labels = data[:, -1].astype('<U14')
d = {'0' : 0, '1' : 1}
labels = np.array([d[x] for x in labels])


In [17]:
df

0     1     2           3         4         5         6     7   \
0     b'a'  b'a'  b'N'  b'15180.0'   b'48.0'  b'-72.0'  b'-72.0'  b'a'   
1     b'a'  b'a'  b'N'  b'14720.0'   b'33.0'  b'-70.0'  b'-79.0'  b'a'   
2     b'a'  b'a'  b'N'   b'8050.0'   b'30.0'  b'-81.0'  b'-78.0'  b'a'   
3     b'a'  b'a'  b'N'  b'28820.0'  b'171.0'  b'-23.0'   b'40.0'  b'a'   
4     b'a'  b'a'  b'N'  b'12640.0'   b'57.0'  b'-63.0'  b'-52.0'  b'a'   
...    ...   ...   ...         ...       ...       ...       ...   ...   
2579  b'b'  b'a'  b'W'  b'81410.0'  b'785.0'  b'432.0'  b'151.0'  b'b'   
2580  b'b'  b'a'  b'W'  b'42110.0'  b'555.0'  b'213.0'  b'118.0'  b'a'   
2581  b'b'  b'a'  b'W'  b'26960.0'  b'540.0'  b'101.0'  b'112.0'  b'a'   
2582  b'a'  b'a'  b'W'  b'16130.0'  b'322.0'    b'2.0'    b'2.0'  b'a'   
2583  b'a'  b'a'  b'W'  b'12750.0'  b'235.0'  b'-10.0'  b'-10.0'  b'a'   

          8       9       10      11      12      13      14      15  \
0     b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
1     b'1.0'  b'0.0'  b'1.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
2     b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
3     b'1.0'  b'0.0'  b'1.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
4     b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
...      ...     ...     ...     ...     ...     ...     ...     ...   
2579  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
2580  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
2581  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
2582  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   
2583  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'  b'0.0'   

             16         17    18  
0        b'0.0'     b'0.0'  b'0'  
1     b'2000.0'  b'2000.0'  b'0'  
2        b'0.0'     b'0.0'  b'0'  
3     b'3000.0'  b'3000.0'  b'0'  
4        b'0.0'     b'0.0'  b'0'  
...         ...        ...   ...  
2579     b'0.0'     b'0.0'  b'0'  
2580     b'0.0'     b'0.0'  b'0'  
2581     b'0.0'     b'0.0'  b'0'  
2582     b'0.0'     b'0.0'  b'0'  
2583     b'0.0'     b'0.0'  b'0'  

[2584 rows x 19 columns]

labels:

In [13]:
print(names[-1])
print(labels)

class
[0 0 0 ... 0 0 0]


categorical features:

In [10]:
print(names[categ_features])
print(x_categ)


['seismic' 'seismoacoustic' 'shift' 'ghazard']
[['a' 'a' 'N' 'a']
 ['a' 'a' 'N' 'a']
 ['a' 'a' 'N' 'a']
 ...
 ['b' 'a' 'W' 'a']
 ['a' 'a' 'W' 'a']
 ['a' 'a' 'W' 'a']]


In [18]:
unique_labels = [np.unique(x_categ[:, i]) for i in range(x_categ.shape[-1])]
print(unique_labels)
categories = tuple(len(x) for x in unique_labels)
print(categories)

[array(['a', 'b'], dtype='<U14'), array(['a', 'b', 'c'], dtype='<U14'), array(['N', 'W'], dtype='<U14'), array(['a', 'b', 'c'], dtype='<U14')]
(2, 3, 2, 3)


In [19]:
def encode_category(data):
    data_ = np.zeros(data.shape)
    uniques = []
    for i in range(data.shape[-1]):
        unique_labels = np.unique(data[:, i])
        uniques.append(len(unique_labels))
        d = dict((x, i) for i, x in enumerate(unique_labels))
        data_[:, i] = np.array([d[x] for x in data[:, i]])
    return data_.astype(int), tuple(uniques)


In [20]:
x_categ_, categories = encode_category(x_categ)
print(x_categ_)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [1 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [25]:
print(categories)

(2, 3, 2, 3)


continuous features:

In [11]:
print(names[cont_features])
print(x_cont)


['genergy' 'gpuls' 'gdenergy' 'gdpuls' 'nbumps' 'nbumps2' 'nbumps3'
 'nbumps4' 'nbumps5' 'nbumps6' 'nbumps7' 'nbumps89' 'energy' 'maxenergy']
[[ 1.518e+04  4.800e+01 -7.200e+01 ...  0.000e+00  0.000e+00  0.000e+00]
 [ 1.472e+04  3.300e+01 -7.000e+01 ...  0.000e+00  2.000e+03  2.000e+03]
 [ 8.050e+03  3.000e+01 -8.100e+01 ...  0.000e+00  0.000e+00  0.000e+00]
 ...
 [ 2.696e+04  5.400e+02  1.010e+02 ...  0.000e+00  0.000e+00  0.000e+00]
 [ 1.613e+04  3.220e+02  2.000e+00 ...  0.000e+00  0.000e+00  0.000e+00]
 [ 1.275e+04  2.350e+02 -1.000e+01 ...  0.000e+00  0.000e+00  0.000e+00]]


In [23]:
x_cont_ = x_cont[:, np.std(x_cont, axis=0) != 0]
x_cont

array([[ 1.518e+04,  4.800e+01, -7.200e+01, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       [ 1.472e+04,  3.300e+01, -7.000e+01, ...,  0.000e+00,  2.000e+03,
         2.000e+03],
       [ 8.050e+03,  3.000e+01, -8.100e+01, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       ...,
       [ 2.696e+04,  5.400e+02,  1.010e+02, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       [ 1.613e+04,  3.220e+02,  2.000e+00, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       [ 1.275e+04,  2.350e+02, -1.000e+01, ...,  0.000e+00,  0.000e+00,
         0.000e+00]])